"""empty message

Revision ID: 6859c6a95f72
Revises: 
Create Date: 2019-04-06 11:51:02.386228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6859c6a95f72"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stupid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=128), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stupid")
    # ### end Alembic commands ###
